#!/bin/bash

# CompasScan - Environment Variables Setup Helper
# Este script te ayuda a configurar todas las variables de entorno

set -e

echo "🔑 CompasScan - Environment Variables Setup"
echo "==========================================="
echo ""

# Colores
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Verificar si .env existe
if [ -f .env ]; then
    echo -e "${YELLOW}⚠️  .env file already exists${NC}"
    echo ""
    read -p "Do you want to backup and recreate it? (y/n): " -n 1 -r
    echo ""
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        cp .env .env.backup.$(date +%Y%m%d_%H%M%S)
        echo -e "${GREEN}✅ Backup created${NC}"
    else
        echo -e "${YELLOW}Exiting...${NC}"
        exit 0
    fi
fi

echo ""
echo -e "${BLUE}📝 Let's configure your environment variables${NC}"
echo ""
echo "You'll need to provide API keys for:"
echo "  1. Google Gemini (Required)"
echo "  2. Supabase (Required)"
echo "  3. Redis/Upstash (Required)"
echo "  4. Logfire (Optional - Observability)"
echo "  5. Sentry (Optional - Error Tracking)"
echo "  6. Brave Search (Optional - Free Search)"
echo "  7. Google Search (Optional - Fallback)"
echo ""
read -p "Press Enter to continue..."
echo ""

# Crear .env
cat > .env << 'EOF'
# CompasScan - Environment Variables
# Generated by setup-env-vars.sh

EOF

# === GEMINI API ===
echo -e "${BLUE}1/7: Google Gemini API${NC}"
echo "Get your key from: https://aistudio.google.com/app/apikey"
read -p "GEMINI_API_KEY: " GEMINI_API_KEY
echo "GEMINI_API_KEY=$GEMINI_API_KEY" >> .env
echo -e "${GREEN}✅ Gemini configured${NC}"
echo ""

# === SUPABASE ===
echo -e "${BLUE}2/7: Supabase Database${NC}"
echo "Get from: https://supabase.com/dashboard/project/_/settings/api"
read -p "SUPABASE_URL: " SUPABASE_URL
read -p "SUPABASE_KEY (anon/public): " SUPABASE_KEY
cat >> .env << EOF

# === Supabase Database ===
SUPABASE_URL=$SUPABASE_URL
SUPABASE_KEY=$SUPABASE_KEY
EOF
echo -e "${GREEN}✅ Supabase configured${NC}"
echo ""

# === REDIS ===
echo -e "${BLUE}3/7: Redis/Upstash Cache${NC}"
echo "Get from: https://console.upstash.com"
read -p "REDIS_URL: " REDIS_URL
cat >> .env << EOF

# === Redis Cache ===
REDIS_URL=$REDIS_URL
REDIS_TTL_GEMINI=86400
REDIS_TTL_GOOGLE=3600
REDIS_TTL_CONTEXT=21600
EOF
echo -e "${GREEN}✅ Redis configured${NC}"
echo ""

# === LOGFIRE ===
echo -e "${BLUE}4/7: Pydantic Logfire (Optional)${NC}"
echo "Get from: https://logfire.pydantic.dev"
read -p "LOGFIRE_TOKEN (press Enter to skip): " LOGFIRE_TOKEN
if [ ! -z "$LOGFIRE_TOKEN" ]; then
    cat >> .env << EOF

# === Observability - Logfire ===
LOGFIRE_TOKEN=$LOGFIRE_TOKEN
EOF
    echo -e "${GREEN}✅ Logfire configured${NC}"
else
    echo -e "${YELLOW}⏭️  Skipped (observability will be disabled)${NC}"
fi
echo ""

# === SENTRY ===
echo -e "${BLUE}5/7: Sentry Error Tracking (Optional)${NC}"
echo "Get from: https://sentry.io"
read -p "SENTRY_DSN (press Enter to skip): " SENTRY_DSN
if [ ! -z "$SENTRY_DSN" ]; then
    cat >> .env << EOF
SENTRY_DSN=$SENTRY_DSN
EOF
    echo -e "${GREEN}✅ Sentry configured${NC}"
else
    echo -e "${YELLOW}⏭️  Skipped (error tracking will be disabled)${NC}"
fi
echo ""

# === BRAVE SEARCH ===
echo -e "${BLUE}6/7: Brave Search API (Optional)${NC}"
echo "Get from: https://brave.com/search/api/"
read -p "BRAVE_API_KEY (press Enter to skip): " BRAVE_API_KEY
if [ ! -z "$BRAVE_API_KEY" ]; then
    cat >> .env << EOF

# === Search API - Brave (Primary) ===
BRAVE_API_KEY=$BRAVE_API_KEY
EOF
    echo -e "${GREEN}✅ Brave Search configured${NC}"
else
    echo -e "${YELLOW}⏭️  Skipped (will use Google Search)${NC}"
fi
echo ""

# === GOOGLE SEARCH ===
echo -e "${BLUE}7/7: Google Custom Search (Optional Fallback)${NC}"
echo "Get from: https://console.cloud.google.com/apis/credentials"
read -p "GOOGLE_API_KEY (press Enter to skip): " GOOGLE_API_KEY
if [ ! -z "$GOOGLE_API_KEY" ]; then
    read -p "GOOGLE_CSE_ID: " GOOGLE_CSE_ID
    cat >> .env << EOF

# === Search API - Google (Fallback) ===
GOOGLE_API_KEY=$GOOGLE_API_KEY
GOOGLE_CSE_ID=$GOOGLE_CSE_ID
EOF
    echo -e "${GREEN}✅ Google Search configured${NC}"
else
    echo -e "${YELLOW}⏭️  Skipped${NC}"
fi
echo ""

# Environment
cat >> .env << EOF

# === Environment ===
VERCEL_ENV=local
EOF

# Resumen
echo ""
echo "=========================================="
echo -e "${GREEN}✅ Configuration Complete!${NC}"
echo "=========================================="
echo ""
echo "📄 File created: .env"
echo ""
echo "Next steps:"
echo "  1. Test locally: uvicorn api.index:app --reload"
echo "  2. Check health: curl http://localhost:8000/health"
echo "  3. Test scan: curl 'http://localhost:8000/?brand=Nike'"
echo ""
echo "For Vercel deployment, see: VERCEL_ENV_SETUP.md"
echo ""

# Verificar archivo
if [ -f .env ]; then
    echo -e "${GREEN}✅ .env file created successfully${NC}"
    echo ""
    echo "File contents (keys hidden):"
    echo "---"
    cat .env | sed 's/=.*/=***/' | head -20
    echo "..."
else
    echo -e "${RED}❌ Error creating .env file${NC}"
    exit 1
fi

echo ""
echo -e "${YELLOW}⚠️  Remember: Never commit .env to git!${NC}"
echo -e "${GREEN}Happy coding! 🚀${NC}"

